vile:
  ignore: [
      "node_modules",
      ".test",
      "coverage",
      "test/fixtures/**"
    ]

depcheck:
  config:
    ignore_dev_deps: false
    ignore_dirs: [ ]
    ignore_deps: [ "pryjs", "bluebird" ]

length:
  config:
    file: 250
    line: 80
  ignore: [ "lib" ]

license:
  config: [
      "MPL-2.0",
      "MIT",
      "MIT*",
      "The MIT License",
      "Public Domain",
      "PSF",
      "BSD",
      "FreeBSD",
      "BSD-like",
      "BSD*",
      "BSD-3-Clause",
      "BSD-2-Clause",
      "BSD-3-Clause AND MIT",
      "Artistic-2.0",
      "(BSD-2-Clause OR MIT OR Apache-2.0)",
      "ISC",
      "WTFPL",
      "(BSD-2-Clause OR WTFPL)",
      "Apache*",
      "Apache License 2.0",
      "Apache 2.0",
      "Apache-2.0",
      "WTFPL"
    ]
